#!/usr/bin/env zsh

export EDITOR="nvim"

# mise
if command -v mise &>/dev/null; then
  eval "$(mise activate zsh)"
fi

# starship
if command -v starship &>/dev/null; then
  eval "$(starship init zsh)"
fi

# zoxide
if command -v zoxide &>/dev/null; then
  eval "$(zoxide init zsh)"
fi

# try
if command -v try &>/dev/null; then
  eval "$(try init ~/Work/tries)"
fi

# fzf
if command -v fzf &>/dev/null; then
  if [[ -f /usr/share/fzf/completion.zsh ]]; then
    source /usr/share/fzf/completion.zsh
  fi
  if [[ -f /usr/share/fzf/key-bindings.zsh ]]; then
    source /usr/share/fzf/key-bindings.zsh
  fi
fi

alias ls="eza -1 --icons=always -F --git --color=always -L 1 --group-directories-first -l --git -a --color-scale=size -h"
alias lsg="ezac --git-ignore"
alias lsa="ezac -a"
alias cat="bat"
alias grep="rg"
alias diff="diff-so-fancy"
alias neofetch="fastfetch"
alias makedb="compiledb -n make"

alias scd="cd"
alias cd="z"
alias cdi="zi"



# lg()
# {
#     export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir
#
#     lazygit "$@"
#
#     if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
#             cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
#             rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
#     fi
# }
